### ISSUE TITLE
Various Cleanup

### ISSUE THREAD

**Issue by gerritdm** [blue-marble/gridpath#17]
**Standardize naming conventions for variables**
- [x] standardize and shorten capacity and operational type names
- [x] standardize and shorten variable names, constraints, and functions (see #278). Edit: Addressed for most of the main modules but not all. 
- [ ] align database columns with tab file columns. They are often still different, e.g. new_binary_build_storage_vintage_costs and new_build_storage_vintage_costs (project vs. vintage). (vintage is perhaps a more general thing that needs to be cleared up since it is not used consistently everywhere). 
- [ ] stop vs. shut down vs. turn off ; start vs. start-up vs. turn on
- [ ] model vs. mod vs. m usage
- [ ] project vs. generator vs. resource (I prefer resource)
- [ ] p vs. g vs. r usage for projects/gen/resource
- [ ] replace dynamic_inputs with dynamic_components throughout code base
- [ ] use `tonnes` to describe carbon emissions (which are in metric tonnes) and avoid confusion with short tons. 
- [ ] rename database tables, input tables and results tables to be in line with the new names of the cap-types and op-types (gen_new_bin_xxxx instead of new_binary_generator_xxx.tab). 

**Code Style**
- [ ] standardize use of string quotes, see #151
- [ ] return None vs. pass 
- [ ] standardize line breaks with long formulas (I suggest to use brackets to avoid "\\" and to put operators at the start of the line. Always separate line for the (in)equality sign?

**Doc Strings**
- [ ] Clarify hydro whether hydro operating characteristics (budget, pmax, pmin) are before or after curtailment and make sure parameter names are consistent (see ##341). 
- [ ] standardize function descriptions. Often the same general functions have slightly different descriptions depending on where they appear, even though they do the same thing (e.g. test_data_loaded_correctly()).
- [ ] standardize input/output type description in function docs 
- [ ] rename prm_group_costs (?) - based on #todo in code
- [ ] clarify that `fuel_burn`, `variable_om`, `carbon_emissions`, and `recs` are all "per timepoint" and not per hour and should be multiplied by the number of hours in the timepoint to get the actual amount ("power" vs. "energy" issue). This could also be clarified by changing the variable name. See #461. 

**Results Formatting**
- [ ] Sort tables before outputting to csv / database (makes comparison a lot easier)
- [x] Round all results to a default precision (e.g. .2f); right now we don't so I get lots of "git modified" hits because the objective function is off by 0.00001. 
- [ ] Standardize use of value()/float()/... when writing out results (seems inconsistent right now)
- [ ] The summary results (summary_results.txt) for binary and linear retirements currently use the same headers, which could be confusing if you are modeling both linear and binary retirements (you would get 2 'Retired Capacity' sections, one with the linear retirements and one with the binary retirements).

**Re-factoring repetitive code**
- [ ] The gen_commit_lin and gen_commit_bin have some code blocks that are used at least twice, such as summing the startup power across all startup types, that could be re-factored into a Pyomo Expression for easier readabilty. Other modules might have similar issues, so this could be a broader look into re-factoring repetitive code into expressions across all subtype modules.
- [ ] The reserve rules are the same in all modules, so could be consolidated, see #329. 
- [ ] The validation of operational characteristics by operational type has lots of repetitive code and hard-coding that makes it cumbersome to add new characteristics (e.g. expected_na_columns had to be updated everywhere in #526). It should be refactored.
- [ ] operational_periods_by_new_build_transmission_vintage could re-use the operational_periods_by_project_vintage functions in capacity_types.common_methods

**Other**
- [ ] Standardize database naming. We're using both 'conn' and 'db' for the same type of sqlite database connection objects (`conn` seems most clear to me; `db` could be the name of the db or the connection, or the path). 
- [ ] Remove redundant passing of both cursor and connection in functions. Since creating cursor is very low overhead, simply pass connection object and create cursor where needed. Examples: `imports_results_into_database` in `import_scenario_results.py`, `process_results.py`, `spin_on_database_lock`. 
- [ ] In some of the modules we use a local `determine_xxx` function to read in inputs, but we often call that function many times (instead of calling it once and assigning it to a variable). 
- [x] Find a way to avoid having to type stdout_original = sys.stdout all the time in run_scenario.py
- [x] Standardize return behavior of run_scenario() to avoid all the if statements
- [ ] The order order of 'temporal' IDs in the table definitions and SQL statements is inconsistent and needs to be standardized.
