### ISSUE TITLE
Various improvements to gen_commit_cap, gen_commit_bin/lin

### ISSUE THREAD

**Issue by anamileva** [blue-marble/gridpath#256]
- [ ] **Look into aligning capacity-commit module with binary-commit module**
- [ ] **Check experimental ramp rate limits capacity commit.** The capacity commit module has some non-conventional ways to break out the startup ramps and the operational ramps. Those are experimental and haven't been tested as thoroughly as they should. See #60.
- [ ] **Skip min up/down constraint for certain timepoints for capacity commit. ** According to Morales-Espana et al. (2013), the min up/down constraint for unit commitment is only applied to [UT, T], where UT is the min up/down time, and T is the horizon length (e.g. 24 hours). This means you can skip the constraint for the first UT-1 hours. We should investigate whether this also applies to the capacity commit module, where we have linear capacity commitment rather than binary commitment, and adjust the constraint
if needed. See #49. 
- [ ] **Harmonize treatment of startup_chars, heat_rate_curves (and vom_curves)**. Right now, all startup_chars inputs and model components are read/created in the individual operational modules, whereas the heat_rate_curves (and variable_om_curves) inputs and model components are read/created in operations.init. Both have their pros and cons. Doing it in the individual operational modules results in repetitive code, whereas doing it in operations.init can make it hard to follow / kludgey (see #TODO comment). Perhaps a long-term solution could be to come up with a class-based structure with inheritance for the operational types so that we can have everything contained within a operational type module, but avoid the repetitive code. See #515.  
- [ ] **Consolidate startup ramp rate and cost inputs.** Right now the startup_ramp rate and cost inputs are in 2 different places, depending on the operational type. The gen_commit_cap operational type, which doesn't have multiple startup types, reads it in from project_operational_chars, whereas the gen_commit_lin and gen_commit_bin operational types read it in from project_startup_chars. We should probably move the inputs for gen_commit_cap into the same startup_chars table to avoid confusion (will create an issue for this). See #447.
- [ ] **Revisit heat rates during startup and shutdown**. We currently use the piecewise linear heat rates regardless of whether we are in a startup/shutdown trajectory or not. It might make sense to use a simple average heat rate (MMBtu/MWh) for startup/shutdown, since the intercept might blow up the average heat rate at very low output levels. See #283. 
- [ ] **Address inefficient ramp management and energy vs. power** (based on Morales-Espana paper; see #245).
