### ISSUE TITLE
Input data checks and validation

### ISSUE THREAD

**Issue by anamileva** [blue-marble/gridpath#6]
- [x] Mismatching operational types (e.g. binary commit and new build)
- [x] New build projects have to be self consistent with new build vintage costs (gen / storage / tx)
- [x] Validate that at least one project is contributing to each reserve/policy/reliability zone. Currently, we can have reserve/policy/reliability zone with no projects that can contribute toward meeting their target, see #347. 
- [x] Disallow combination of certain availability types and capacity types. Since capacity is multiplied by derate, we can't allow combinations of availability types and capacity types where both are decision variables. That means we have to disallow endogenous availability derates and new build or retirement capacity types. See #249. Edit: closing since non-linear problems are actually okay, just harder to solve. 
- [ ] Provide useful error messages when the wrong key words are given to e.g run_scenario.py; right now the original wrong keyword error is obscured and the model will fail at a later stage; see #111. 
- [x] Validate missing var profiles (right now just a warning, see discussion in #543). 
- [x] Validate that hydro avg is between min and max.
- [ ] Validate that the horizons specified in structure.csv matched those in horizon_params.csv (or the equivalent database tables). 
- [x] add basic general validation to capacity types similar to operational types
- [ ] Validate that fully deliverable energy iimited projects are assigned a min duration for full cap credit (removed in #605)
- [ ] Validate that energy only allowed projects are assigned a deliverability group and that other types don’t have one (removed in #605)
- [ ] Check that all 'fully_deliverable_energy_limited' projects are assigned a min_duration_for_full_capacity_credit_hours
- [ ] Check if all ''energy_only_allowed' projects are assigned a 'deliverability group' and that other types are not assigned one
- [ ] Mismatched temporal setup and project balancing types (e.g. #819)
